### ISSUE TITLE
xsys key 'split' is not unique error

### ISSUE THREAD

**Issue by gokceneraslan** [stepelu/lua-rclient#2]
Hi,

I am getting the error below:

```
> local r = require 'rclient'
...e/x/Code/install/share/lua/5.1/trepl/init.lua:363: 
...e/x/Code/install/share/lua/5.1/trepl/init.lua:363: 
...e/x/Code/install/share/lua/5.1/trepl/init.lua:363: 
...e/x/Code/install/share/lua/5.1/trepl/init.lua:363: 
...e/x/Code/install/share/lua/5.1/xsys/_xsys.lua:35: 
key 'split' is not unique among tables to be merged
stack traceback:
    [C]: in function 'error'
    ...e/x/Code/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
    [string "local r = require 'rclient'"]:1: in main chunk
    [C]: in function 'xpcall'
    ...e/x/Code/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
    ...Code/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
    [C]: at 0x00405
```

I just copied xsys and rclient directories to `luarocks` directory.

**Comment by stepelu** [comment]
It seems that you are using trepl and I cannot easily see what originates the error (i.e. what calls `xsys.union()` which is where the error happens).

The issue could be that your global table `string` already has `string.split()` defined, which should not be the case in standard Lua(JIT).

Also, you copied the directories form ULua of from GitHub exports?

**Comment by gokceneraslan** [comment]
You are right, `require 'rclient'` works properly from within `luajit` but not working in torch's `th` thingy. Maybe because `th` loads `xlua` module of torch and `string.split` is already defined in `xlua` module:

https://github.com/torch/xlua/blob/master/init.lua#L681

I am new to lua, so I didn't really get what you mean by `ULua from GitHub exports`

**Comment by stepelu** [comment]
Well yes, `xlua` modifies the standard libraries. 
IMHO no module should ever do that.

Anyway, I have updated `xsys` (this issue is not related to `rclient`) so that it's now robust to this kind of abuse.

I meant: how exactly did you get the xsys and rclient libraries?

**Comment by gokceneraslan** [comment]
Perfect! Thanks a lot. It's working with new `xsys` now. I got `xsys` and `rclient` exports from git master branch and just copied it to luarocks directory.
